[package]
name = "barrel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.4"
colored = "2.0.0"
globset = "0.4.10"
regex = "1.7.1"
